language: node_js
node_js: lts/*

os:
  - linux
  - osx
  - windows

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libx11-dev
      - zlib1g-dev
      - libpng12-dev
      - libxtst-dev
      - g++-4.8
      - gcc-4.8
      - rpm

script: npm run dist
