language: node_js
node_js: lts/*

os:
  - linux
  - osx
  - windows

addons:
  apt:
    packages:
      - libx11-dev
      - zlib1g-dev
      - libpng-dev
      - libxtst-dev
      - rpm

script:
  - npm run dist
